### ISSUE TITLE
Missing UV index

### ISSUE THREAD

**Issue by rootasjey** [jcheng31/DarkSkyApi#21]
Hello,

It seems that the *uvIndex* and *uvIndexTime* information is missing on Data Point Object.
I've seen that the property is available when I make an HTTP request from a browser.

[See the official doc](https://darksky.net/dev/docs)

**Comment by rootasjey** [comment]
Created a pull request here https://github.com/jcheng31/DarkSkyApi/pull/22

**Comment by jcheng31** [comment]
Hey, sorry for the delay - thanks a lot for doing this! I'll merge it in and release an update soon :)

**Comment by rootasjey** [comment]
You're welcome. Thank you for the merge :)
