### ISSUE TITLE
Release a new package w/ UV index data

### ISSUE THREAD

**Issue by rootasjey** [jcheng31/DarkSkyApi#23]
Hello,

I sent [a pull request](https://github.com/jcheng31/DarkSkyApi/pull/22) some time ago with UV index data, but there's no new available package from [Nuget](https://www.nuget.org/packages/DarkSkyApi/).

Could you please release a new one with the update ?

Thanks.

**Comment by jcheng31** [comment]
Ah, I dropped the ball here - v3.2.1 is now out on Nuget with your changes. Thanks a lot!

**Comment by rootasjey** [comment]
Thank you too 😄
