### ISSUE TITLE
Missing severity on Alerts class

### ISSUE THREAD

**Issue by MattLugar** [jcheng31/DarkSkyApi#25]
Might be a new item on the Alerts definition, but doesn't seem to be defined in the Forecast class

https://darksky.net/dev/docs#response-format

Alerts Array

The alerts array contains objects representing the severe weather warnings issued for the requested location by a governmental authority (please see our data sources page for a list of sources). Objects in the alerts array contain the following properties:

description required
A detailed description of the alert.
expires required
The UNIX time at which the alert will expire.
regions required
An array of strings representing the names of the regions covered by this weather alert.
**severity required
The severity of the weather alert. Will take one of the following values: "advisory" (an individual should be aware of potentially severe weather), "watch" (an individual should prepare for potentially severe weather), or "warning" (an individual should take immediate action to protect themselves and others from potentially severe weather).**
time required
The UNIX time at which the alert was issued.
title required
A brief description of the alert.
uri required
An HTTP(S) URI that one may refer to for detailed information about the alert.

**Comment by jcheng31** [comment]
Ah, yep, that looks like a new field. I'll get to it soon!

**Comment by MattLugar** [comment]
Love how smoothly this works!

Looking like they've updated quite a few fields since this last version came out, but I noticed these were missing that I was trying to use as well on Forecast.data[].Daily:

**temperatureHigh** optional, only on daily
The daytime high temperature.
**temperatureHighTime** optional, only on daily
The UNIX time representing when the daytime high temperature occurs.
**temperatureLow** optional, only on daily
The overnight low temperature.
**temperatureLowTime** optional, only on daily
The UNIX time representing when the overnight low temperature occurs.

**Comment by jcheng31** [comment]
Hmm, those should be there - `DayDataPoint` has `MaxTemperatureTime`, `MaxTemperature`, `MinTemperatureTime`, and `MinTemperature` properties. Are those the ones you're looking for?

**Comment by MattLugar** [comment]
No, I see the `MaxTemperatureTime`, `MaxTemperature`, `MinTemperatureTime`, and `MinTemperature`. Those are depreciated according to the docs [https://darksky.net/dev/docs#response-format](url).

Dark Sky has added `temperatureHigh`, `temperatureHighTime`, `temperatureLow`, `temperatureLowTime`.  Also it looks like `apparentTemperatureHigh`, `apparentTemperatureHighTime`, `apparentTemperatureLow`, and `apparentTemperatureLowTime` are listed as depreciated and `apparentTemperatureMax`, `apparentTemperatureMaxTime`, `apparentTemperatureMin`, and `apparentTemperatureMinTime` have been added to the data set (though I'm not utilizing them on my current project).

There's a distinct difference between the functionality of `temperatureMax` versus `temperatureHigh` when you're talking current day daily forecast.  For example if you get the daily forecast for today at 5PM you may have a `temperatureMax` of 80 but a `temperatureHigh` of 70. The max temperature of 80 might have been reached at 3PM (`temperatureMaxTime`), but since the temperature is in the evening decline, the highest the temperature will be the remainder of the dat will be 70, which is want to display for my "Today" forecast given the app I'm building.

**Comment by MattLugar** [comment]
Found a couple more missing.  `forecast.daily.days[x].windGust` and `forecast.daily.days[x].windGustTime`

**Comment by jcheng31** [comment]
Ah, thanks. I'll get to adding these this weekend; sorry for the delay!

**Comment by MattLugar** [comment]
No worries on the delay, the API works so smoothly and I absolutely love it!!!  I keep finding a few more new attributes missing as I keep working on my project.  Guessing Dark Sky did some major updates to their dataset lately.

daily and hourly subsets have `precipAccumulation` for snow now as well. :)

**Comment by jcheng31** [comment]
(Haven't forgotten about this - just been extremely busy recently. I've got the severity field added on a local branch, and will get to the others ASAP.)

**Comment by jcheng31** [comment]
Alright, just published v3.3 on Nuget, which includes everything here. Thanks for your patience :)
